Support reading the installed game off the SD card directly
TKMM-Team/TkSharp pull request #1
Opened 2024-12-29 21:31 UTC by MasterBubbles

This adds a new implementation that allows the user to read the installed game directly off the SD card of their Switch (using the `Nintendo/Contents` folder at the root of the card, or in emuMMC).

The only thing that isn't properly implemented is the RelayCommand on the settings of TkSharp.DevTool, but it works in TkSharp.Debug

In the future, new implementations could be added to allow the use of different combinations, for example selecting XCI for the base game (for users with cartridges dumps) and SD card for the update.

2025-01-04 01:33 UTC, ArchLeaders requested changes

2025-01-04 01:33 UTC, ArchLeaders commented on Extensions/TkSharp.Extensions.LibHac/Extensions/FileSystemExtensions.cs
> +        return buffer.SequenceEqual(stackalloc byte[] { (byte)'H', (byte)'E', (byte)'A', (byte)'D' });
This can be simplified.

```suggestion
        return buffer.SequenceEqual("HEAD"u8);
```

2025-01-04 01:33 UTC, ArchLeaders commented on Extensions/TkSharp.Extensions.LibHac/TkRom.cs
> +    }
Redundant default values should be removed, properties should be made read-only and Initialize() should be inlined to support this.

Consistent formatting should also be used.

```suggestion
    public int GameVersion { get; }

    public string NsoBinaryId { get; }

    public TkZstd Zstd { get; }

    public IDictionary<string, string> AddressTable { get; }

    public Dictionary<string, string>.AlternateLookup<ReadOnlySpan<char>> EventFlowVersions { get; }

    public Dictionary<string, string>.AlternateLookup<ReadOnlySpan<char>> EffectVersions { get; }

    public TkRom(TkChecksums checksums, IFileSystem fileSystem)
    {
        _checksums = checksums;
        _fileSystem = fileSystem;

        using (Stream regionLangMaskFs = _fileSystem.OpenFileStream("/System/RegionLangMask.txt"))
        using (RentedBuffer<byte> regionLangMask = RentedBuffer<byte>.Allocate(regionLangMaskFs)) {
            GameVersion = RegionLangMaskParser.ParseVersion(regionLangMask.Span, out string nsoBinaryId);
            NsoBinaryId = nsoBinaryId;
        }

        using (Stream zsDicFs = _fileSystem.OpenFileStream("/Pack/ZsDic.pack.zs")) {
            Zstd = new TkZstd(zsDicFs);
        }

        using (Stream addressTableFs = _fileSystem.OpenFileStream($"/System/AddressTable/Product.{GameVersion}.Nin_NX_NVN.atbl.byml.zs"))
        using (RentedBuffer<byte> addressTableBuffer = RentedBuffer<byte>.Allocate(addressTableFs)) {
            AddressTable = AddressTableParser.ParseAddressTable(addressTableBuffer.Span, Zstd);
        }

        using (Stream eventFlowFileEntryFs = _fileSystem.OpenFileStream($"/{AddressTable["Event/EventFlow/EventFlowFileEntry.Product.byml"]}.zs"))
        using (RentedBuffer<byte> eventFlowFileEntryBuffer = RentedBuffer<byte>.Allocate(eventFlowFileEntryFs)) {
            EventFlowVersions = EventFlowFileEntryParser.ParseFileEntry(eventFlowFileEntryBuffer.Span, Zstd);
        }

        using (Stream effectInfoFs = _fileSystem.OpenFileStream($"/{AddressTable["Effect/EffectFileInfo.Product.Nin_NX_NVN.byml"]}.zs"))
        using (RentedBuffer<byte> effectInfoBuffer = RentedBuffer<byte>.Allocate(effectInfoFs)) {
            EffectVersions = EffectInfoParser.ParseFileEntry(effectInfoBuffer.Span, Zstd);
        }
    }
```

2025-01-04 01:33 UTC, ArchLeaders commented on Extensions/TkSharp.Extensions.LibHac/TkRomHelper.cs
> +        var localFsRef = new UniqueRef<IAttributeFileSystem>(localFs);
This is either never disposed, or collected by the GC which may cause instability elsewhere.

IDisposables must be collected and properly handled by the top-level class (the one stored by the caller to interact).

2025-01-04 01:33 UTC, ArchLeaders commented on Extensions/TkSharp.Extensions.LibHac/TkRomHelper.cs
> +        string keysPath,
Keys should be passed in as a `KeySet` object to be consistent with `PackedTkRom` and to remove redundancy by the caller.

2025-01-04 01:33 UTC, ArchLeaders commented on Tools/TkSharp.DevTools/Helpers/RomHelper.cs
> +            return null;
This function should never return null.

2025-01-04 01:52 UTC, MasterBubbles commented on Extensions/TkSharp.Extensions.LibHac/TkRomHelper.cs
> +        string keysPath,
`PackedTkRom` is intended to be removed completely so there is no need to keep consistency with it

2025-01-04 01:54 UTC, ArchLeaders commented on Extensions/TkSharp.Extensions.LibHac/TkRomHelper.cs
> +        string keysPath,
The second part of my sentence is more important, and should still be observed. (As discussed on Discord)

2025-01-04 03:08 UTC, MasterBubbles commented on Extensions/TkSharp.Extensions.LibHac/TkRomHelper.cs
> +        var localFsRef = new UniqueRef<IAttributeFileSystem>(localFs);
Well, I'm not entirely sure I did that correctly, so I'll let you test it whenever you can and let me know if there are any issues

2025-01-04 03:10 UTC, ArchLeaders commented on Extensions/TkSharp.Extensions.LibHac/TkRomHelper.cs
> +        var localFsRef = new UniqueRef<IAttributeFileSystem>(localFs);
I can see that many of the FileSystem's are still undisposed, but I'll figure something out. Thanks!

2025-01-07 00:37 UTC, ArchLeaders requested changes
In general, file-scoped namespaces are preferred, however, I can automate that fix later in Rider

2025-01-07 00:37 UTC, ArchLeaders commented on TkSharp.Debug/DebugRomProvider.cs
> +        var romProvider = new LibHacRomProvider();
The rom provider is never disposed

2025-01-07 00:37 UTC, ArchLeaders commented on Tools/TkSharp.DevTools/Helpers/RomHelper.cs
> +        Console.WriteLine($"Reading base game from {baseSource} and update from {updateSource}");
Prefer TkLog.Instance for logging

2025-01-07 00:41 UTC, LordBubblesDev commented on Tools/TkSharp.DevTools/Helpers/RomHelper.cs
> +        Console.WriteLine($"Reading base game from {baseSource} and update from {updateSource}");
Oops, I had left that for testing to ensure it was using the correct sources, guess I forgot

2025-01-07 00:58 UTC, LordBubblesDev commented on TkSharp.Debug/DebugRomProvider.cs
> +        var romProvider = new LibHacRomProvider();
Hopefully now it's fixed

2025-01-07 10:06 UTC, LordBubblesDev commented on TkSharp.Debug/DebugRomProvider.cs
> +        var romProvider = new LibHacRomProvider();
(btw I thought it wasn't necessary, considering TkSharp.Debug loads the rom provider once, merges mods then closes completely)

2025-01-07 19:49 UTC, ArchLeaders commented on TkSharp.Debug/DebugRomProvider.cs
> +        var romProvider = new LibHacRomProvider();
I'm not looking at the context, I just know that it should be disposed.

2025-01-07 19:52 UTC, LordBubblesDev commented on TkSharp.Debug/DebugRomProvider.cs
> +        var romProvider = new LibHacRomProvider();
Ok, should be fixed now 👍

2025-01-07 19:54 UTC, ArchLeaders commented on TkSharp.Debug/DebugRomProvider.cs
> +        var romProvider = new LibHacRomProvider();
This class is used as a singleton, so even though it's IDisposable, it's never disposed because the instance is not used in a context.

This isn't important for this specific scenario, but should be noted for other uses.

2025-01-07 23:52 UTC, merged